# 1.将如下“朝向”列中的中文内容 进行 Get_dummies哑变量处理

In [9]:
#补充代码
import pandas as pd
df = pd.DataFrame({'房屋编号': [1, 2, 3, 4, 5, 6], '朝向': ['东', '南', '西', '东北', '南', '西北']})
df_dummies = pd.get_dummies(df, columns=['朝向'])
df_dummies

   房屋编号   朝向_东  朝向_东北   朝向_南   朝向_西  朝向_西北
0     1   True  False  False  False  False
1     2  False  False   True  False  False
2     3  False  False  False   True  False
3     4  False   True  False  False  False
4     5  False  False   True  False  False
5     6  False  False  False  False   True

# 2.将如下“城市”列中的中文内容 进行 Label Encoding编号处理

In [10]:
#补充代码
from sklearn.preprocessing import LabelEncoder
df = pd.DataFrame({'编号': [1, 2, 3, 4, 5, 6], '城市': ['北京', '上海', '南京', '深圳', '北京', '盐城']})
le = LabelEncoder()
df['城市'] = le.fit_transform(df['城市'])
df

   编号  城市
0   1   1
1   2   0
2   3   2
3   4   3
4   5   1
5   6   4

# 3.将如下表格进行min-max标准化

In [11]:
#补充代码
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
X = pd.DataFrame({'年龄': [50, 60, 40, 80, 90], '收入': [20000, 10000, 10000, 30000, 20000]})
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X_scaled

    年龄   收入
0  0.2  0.5
1  0.4  0.0
2  0.0  0.0
3  0.8  1.0
4  1.0  0.5

# 4.将如下表格进行Z-score标准化

In [12]:
#补充代码
import pandas as pd
from sklearn.preprocessing import StandardScaler
X = pd.DataFrame({'年龄': [50, 60, 40, 80, 90], '收入': [20000, 10000, 10000, 30000, 20000]})
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X_scaled

         年龄        收入
0 -0.754829  0.267261
1 -0.215666 -1.069045
2 -1.293993 -1.069045
3  0.862662  1.603567
4  1.401826  0.267261

# 5.过采样和欠采样

In [13]:
# 5.1 案例实战 - 员工离职预测模型（过采样）
# （1）读取代码所在文件夹中的“员工离职预测模型.xlsx”；
# （2）通过随机过采样法进行过采样；
# （3）通过SMOTE过采样法进行过采样；
#编写代码完成上述任务
import pandas as pd
from imblearn.over_sampling import RandomOverSampler, SMOTE

df = pd.read_excel('员工离职预测模型.xlsx')
X = df.drop(columns=['离职'])
X = pd.get_dummies(X)
y = df['离职']

ros = RandomOverSampler(random_state=0)
X_ros, y_ros = ros.fit_resample(X, y)

smote = SMOTE(random_state=0)
X_smote, y_smote = smote.fit_resample(X, y)
X_smote, y_smote

(            满意度      考核得分  工程数量  月工时  工龄   工资_中   工资_低   工资_高
 0      3.800000  0.530000     2  157   3  False   True  False
 1      8.000000  0.860000     5  262   6   True  False  False
 2      1.100000  0.880000     7  272   4   True  False  False
 3      7.200000  0.870000     5  223   5  False   True  False
 4      3.700000  0.520000     2  159   3  False   True  False
 ...         ...       ...   ...  ...  ..    ...    ...    ...
 22851  3.735503  0.568225     2  133   3  False   True  False
 22852  4.095100  0.473920     2  131   3   True  False  False
 22853  3.900000  0.510000     2  129   3  False   True  False
 22854  4.400000  0.536499     2  127   3   True  False  False
 22855  4.400000  0.537764     2  149   3  False   True  False

 [22856 rows x 8 columns],
 0        1
 1        1
 2        1
 3        1
 4        1
         ..
 22851    1
 22852    1
 22853    1
 22854    1
 22855    1
 Name: 离职, Length: 22856, dtype: int64)

In [14]:
# # 3.案例实战 - 员工离职预测模型（欠采样）
# （1）读取代码所在文件夹中的“员工离职预测模型.xlsx”；
# （2）通过随机欠采样法进行过采样；
#编写代码完成上述任务
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler

df = pd.read_excel('员工离职预测模型.xlsx')
X = df.drop(columns=['离职'])
X = pd.get_dummies(X)
y = df['离职']

rus = RandomUnderSampler(random_state=0)
X_rus, y_rus = rus.fit_resample(X, y)
X_rus, y_rus

(       满意度  考核得分  工程数量  月工时  工龄   工资_中   工资_低   工资_高
 13939  5.2  0.63     3  233   3   True  False  False
 9876   5.5  0.97     4  267   4   True  False  False
 7520   7.4  0.83     4  142   3   True  False  False
 12632  7.0  0.76     4  173   2   True  False  False
 8464   5.0  0.57     3  219   3   True  False  False
 ...    ...   ...   ...  ...  ..    ...    ...    ...
 3567   3.7  0.48     2  160   3  False   True  False
 3568   3.7  0.53     2  143   3  False   True  False
 3569   1.1  0.96     6  280   4  False   True  False
 3570   3.7  0.52     2  158   3  False   True  False
 3571   8.1  0.70     6  161   4   True  False  False

 [7144 rows x 8 columns],
 13939    0
 9876     0
 7520     0
 12632    0
 8464     0
         ..
 3567     1
 3568     1
 3569     1
 3570     1
 3571     1
 Name: 离职, Length: 7144, dtype: int64)