# 1.将如下“朝向”列中的中文内容 进行 Get_dummies哑变量处理

In [1]:
#补充代码
import pandas as pd
df = pd.DataFrame({'房屋编号': [1, 2, 3, 4, 5, 6], '朝向': ['东', '南', '西', '东北', '南', '西北']})
df_dummies = pd.get_dummies(df, columns=['朝向'])
df_dummies

   房屋编号   朝向_东  朝向_东北   朝向_南   朝向_西  朝向_西北
0     1   True  False  False  False  False
1     2  False  False   True  False  False
2     3  False  False  False   True  False
3     4  False   True  False  False  False
4     5  False  False   True  False  False
5     6  False  False  False  False   True

# 2.将如下“城市”列中的中文内容 进行 Label Encoding编号处理

In [2]:
#补充代码
from sklearn.preprocessing import LabelEncoder
df = pd.DataFrame({'编号': [1, 2, 3, 4, 5, 6], '城市': ['北京', '上海', '南京', '深圳', '北京', '盐城']})
le = LabelEncoder()
df['城市'] = le.fit_transform(df['城市'])
df

   编号  城市
0   1   1
1   2   0
2   3   2
3   4   3
4   5   1
5   6   4

# 3.将如下表格进行min-max标准化

In [3]:
#补充代码
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
X = pd.DataFrame({'年龄': [50, 60, 40, 80, 90], '收入': [20000, 10000, 10000, 30000, 20000]})
scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X_scaled

    年龄   收入
0  0.2  0.5
1  0.4  0.0
2  0.0  0.0
3  0.8  1.0
4  1.0  0.5

# 4.将如下表格进行Z-score标准化

In [4]:
#补充代码
import pandas as pd
from sklearn.preprocessing import StandardScaler
X = pd.DataFrame({'年龄': [50, 60, 40, 80, 90], '收入': [20000, 10000, 10000, 30000, 20000]})
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X_scaled

         年龄        收入
0 -0.754829  0.267261
1 -0.215666 -1.069045
2 -1.293993 -1.069045
3  0.862662  1.603567
4  1.401826  0.267261

# 5.过采样和欠采样

In [5]:
# 5.1 案例实战 - 员工离职预测模型（过采样）
# （1）读取代码所在文件夹中的“员工离职预测模型.xlsx”；
# （2）通过随机过采样法进行过采样；
# （3）通过SMOTE过采样法进行过采样；
#编写代码完成上述任务

In [6]:
# # 3.案例实战 - 员工离职预测模型（欠采样）
# （1）读取代码所在文件夹中的“员工离职预测模型.xlsx”；
# （2）通过随机欠采样法进行过采样；
#编写代码完成上述任务